/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import List.List;
import User.NewsFeed;
import User.Pegawai;
import User.Pekerjaan;
import adminProperties.tabelControl;
import backgroundProcess.koneksi;

import java.awt.BorderLayout;
import java.awt.Color;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import java.text.*;
import java.awt.print.*;
import javax.swing.JTable;
import java.awt.print.Book;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable.PrintMode;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Dimas Adiyaksa
 */
public class pegawai extends javax.swing.JFrame {

    /**
     * Creates new form KaryawanGUI
     */
    List data = new List();
    Pegawai peg = new Pegawai();
    tabelControl tc = new tabelControl();
    
    public pegawai(Pegawai peg) {
        initComponents();
        this.peg = peg;
        data.read();
        jPanel6.setVisible(true);
        //jPanel3.setVisible(false);
        loadJob();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        loadChart();
        feedUpdate(feedArea);
        inisiasi();
        toPrint.setVisible(false);
        statusCBox1.setVisible(false);
        feedArea.setEditable(false);
        // jXImageView1.setImage(tes.jpg);
        
    }

    private pegawai() {
        initComponents();
        //jPanel3.setVisible(false);
        loadJob();
        jPanel6.setVisible(true);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        toPrint.setVisible(false);
        feedUpdate(feedArea);
        OutIcon("C://Users/Dimas Adiyaksa/"
                      + "Documents/NetBeansProjects/SistemManajemenPegawai"
                      + "/src/EksternalSource/index.png");
       
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupCetak = new javax.swing.ButtonGroup();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        statusCBox1 = new javax.swing.JComboBox<>();
        statusLabel1 = new javax.swing.JLabel();
        NIMPeg = new javax.swing.JTextField();
        nmPeg = new javax.swing.JTextField();
        jab = new javax.swing.JLabel();
        Dep = new javax.swing.JLabel();
        TTL = new org.jdesktop.swingx.JXDatePicker();
        GDLab = new javax.swing.JLabel();
        GDCBox = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        jLabel37 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel38 = new javax.swing.JLabel();
        Kontrak = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        gjTotLab = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        gjPokLab = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lembur = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        bonus = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        namaHai = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NamaLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JabatanLab = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        depLab = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabeltim = new javax.swing.JTable();
        timBagian = new javax.swing.JLabel();
        tim = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableJob = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        dep = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        defineJob = new javax.swing.JTextArea();
        deadline = new org.jdesktop.swingx.JXDatePicker();
        jLabel14 = new javax.swing.JLabel();
        tambahPekerjaan = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        deljob = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        feedArea = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelSlip = new javax.swing.JTable();
        cetakButton = new javax.swing.JButton();
        toPrint = new javax.swing.JTextArea();
        chartPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        out = new javax.swing.JLabel();

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));

        jLabel25.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel25.setText("NIP                  :");

        jLabel26.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel26.setText("Nama             :");

        jLabel27.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel27.setText("Jabatan         :");

        jLabel28.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel28.setText("Departemen :");

        jLabel29.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel29.setText("TTL                   :");

        jLabel30.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel30.setText("Gol Darah      :");

        jLabel31.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel31.setText("Alamat          :");

        jLabel32.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel32.setText("Status            :");

        jLabel33.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel33.setText("Gaji                :");

        statusCBox1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        statusCBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        statusLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        statusLabel1.setText("jLabel21");

        NIMPeg.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        NIMPeg.setText("jTextField1");

        nmPeg.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        nmPeg.setText("jTextField2");

        jab.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jab.setText("jLabel21");

        Dep.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        Dep.setText("jLabel22");

        GDLab.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        GDLab.setText("A");

        GDCBox.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        GDCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "O", "AB" }));

        address.setColumns(20);
        address.setRows(5);
        jScrollPane5.setViewportView(address);

        jLabel37.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel37.setText("jLabel24");

        jButton2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButton2.setText("Edit");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel38.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel38.setText("Kontrak         :");

        Kontrak.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        Kontrak.setText("jLabel11");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Dep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TTL, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GDLab, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GDCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel33)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel31)
                                        .addComponent(jLabel32))
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addGap(7, 7, 7)
                                            .addComponent(statusLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(statusCBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(jButton2))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel26)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(nmPeg))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel25)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(NIMPeg, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel38)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Kontrak)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(365, 365, 365))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(NIMPeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(nmPeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(jab))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(Dep))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(TTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(GDLab)
                            .addComponent(GDCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(statusLabel1)
                            .addComponent(statusCBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(jLabel37))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Kontrak)
                            .addComponent(jLabel38))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );

        jScrollPane4.setViewportView(jPanel5);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        gjTotLab.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        gjTotLab.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel8.setText("Gaji Pokok                  : ");

        gjPokLab.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        gjPokLab.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel7.setText("Jumlah Hari Lembur   :");

        lembur.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lembur.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lembur.setText("3");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel10.setText("Bonus                           :");

        bonus.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        bonus.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bonus.setText("500000");

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel12.setText("Gaji Total                     :");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem Informasi Pegawai");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jPanel4.setBackground(new java.awt.Color(0, 153, 204));

        jTabbedPane1.setBackground(new java.awt.Color(255, 0, 0));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel1FocusGained(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setText("Selamat Datang, ");

        namaHai.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        namaHai.setText("Nama");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setText("Nama             :");
        jLabel4.setToolTipText("");

        NamaLabel.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        NamaLabel.setText("Nama");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setText("Status              :");

        statusLabel.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        statusLabel.setText("Aktif/Cuti");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel6.setText("Jabatan         :");

        JabatanLab.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        JabatanLab.setText("Direktur");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setText("Departemen : ");

        depLab.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        depLab.setText("Produksi");

        tabeltim.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No", "Nama", "Jabatan", "Alamat"
            }
        ));
        jScrollPane2.setViewportView(tabeltim);

        timBagian.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        timBagian.setText("TIM");

        tim.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tim.setText("jLabel9");

        tableJob.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableJob.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableJobMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tableJob);

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel11.setText("Pekerjaan Departemen");

        dep.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        dep.setText("jLabel13");

        jPanel6.setBackground(new java.awt.Color(0, 153, 204));

        defineJob.setColumns(20);
        defineJob.setRows(5);
        jScrollPane7.setViewportView(defineJob);

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Deadline :");

        tambahPekerjaan.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tambahPekerjaan.setText("Tambah");
        tambahPekerjaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahPekerjaanActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Tambah Pekerjaan");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deadline, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tambahPekerjaan))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tambahPekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deadline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))))
                .addGap(12, 12, 12))
        );

        deljob.setText("Hapus");
        deljob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deljobActionPerformed(evt);
            }
        });

        feedArea.setBackground(new java.awt.Color(204, 255, 255));
        feedArea.setColumns(20);
        feedArea.setLineWrap(true);
        feedArea.setRows(5);
        feedArea.setWrapStyleWord(true);
        feedArea.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "News Feed", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Century Gothic", 0, 18))); // NOI18N
        jScrollPane9.setViewportView(feedArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(timBagian)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tim))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(NamaLabel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(statusLabel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JabatanLab))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(depLab))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(namaHai)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dep)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deljob, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane9)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(namaHai))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(NamaLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(statusLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(JabatanLab))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(depLab))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timBagian)
                    .addComponent(tim)
                    .addComponent(jLabel11)
                    .addComponent(dep))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deljob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(54, 54, 54))
        );

        jTabbedPane1.addTab("Beranda", jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        tabelSlip.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "Nama", "Tanggal", "Jumlah", "Keterangan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelSlip);

        cetakButton.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        cetakButton.setText("Cetak Slip");
        cetakButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakButtonActionPerformed(evt);
            }
        });

        toPrint.setBackground(new java.awt.Color(204, 255, 255));
        toPrint.setColumns(20);
        toPrint.setRows(5);

        chartPanel1.setBackground(new java.awt.Color(102, 204, 255));
        chartPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chartPanel1MouseClicked(evt);
            }
        });
        chartPanel1.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(toPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cetakButton)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(chartPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                    .addComponent(chartPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cetakButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(toPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Informasi Gaji", jPanel2);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sistem Informasi Pegawai");

        out.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EksternalSource/index.png"))); // NOI18N
        out.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                outMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(out, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(out, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cetakButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakButtonActionPerformed
        // TODO add your handling code here:
      
    /*    MessageFormat header = new MessageFormat("SLIP Gaji");
        MessageFormat footer = new MessageFormat("Halaman{0,number,integer}");
       
        try{
            tabelSlip.print(JTable.PrintMode.FIT_WIDTH, header, footer);
            
        }catch(java.awt.print.PrinterException e){
            System.err.format("Gagal Mencetak %s%n", e.getMessage());
        }
        */
    print();
    }//GEN-LAST:event_cetakButtonActionPerformed

    private void chartPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chartPanel1MouseClicked
        loadChart();
        // TODO add your handling code here:
    }//GEN-LAST:event_chartPanel1MouseClicked

    private void tambahPekerjaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahPekerjaanActionPerformed
        // TODO add your handling code here:
        koneksi kon = new koneksi();
        DateFormat dtform = new SimpleDateFormat("yyyy-MM-dd");
        if(defineJob.equals("")||deadline.getDate().equals(null)){
            JOptionPane.showMessageDialog(null, "Tanggal atau Pekerjaan tidak boleh kosong");
        }else{
            data.tambahJob(new Pekerjaan(peg.getDept(),defineJob.getText(),dtform.format(deadline.getDate())));
            kon.exec("INSERT INTO `jobdepartemen`(`Departemen`, `Pekerjaan`,"
                + " `Deadline`) VALUES ('"+peg.getDept()+"','"+defineJob.getText()+"','"
                +dtform.format(deadline.getDate())+"')");
            loadJob();
        }
        
    }//GEN-LAST:event_tambahPekerjaanActionPerformed

    private void tableJobMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableJobMouseClicked
        // TODO add your handling code here:
        if(tableJob.getSelectedRow() == -1){
            deljob.setEnabled(false);
        }else{
            deljob.setEnabled(true);
        }
    }//GEN-LAST:event_tableJobMouseClicked

    private void jPanel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1FocusGained
        // TODO add your handling code here:
        if(tableJob.getSelectedRow() == -1){
            deljob.setEnabled(false);
        }else{
            deljob.setEnabled(true);
        }
    }//GEN-LAST:event_jPanel1FocusGained

    private void deljobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deljobActionPerformed
        // TODO add your handling code here:
        
        data.delJob(new Pekerjaan(tableJob.getValueAt(tableJob.getSelectedRow(), 1).toString(),
            tableJob.getValueAt(tableJob.getSelectedRow(), 2).toString(),
                tableJob.getValueAt(tableJob.getSelectedRow(), 3).toString()));
        loadJob();
    }//GEN-LAST:event_deljobActionPerformed

    private void outMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_outMouseClicked
        // TODO add your handling code here:
        login l = new login();
        l.toFront();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_outMouseClicked

    public void loadJob(){
        tc.tabelPekerjaan(tableJob, peg.getDept());
    }
    
    public void print(){
  
        PrinterJob job = PrinterJob.getPrinterJob();
        MessageFormat[] header = new MessageFormat[4];
        header[0] = new MessageFormat("");
        header[1] = new MessageFormat("                                                    "
                + "                                  SLIP GAJI");
        header[2] = new MessageFormat("              NIP : "+peg.getNIP());
        header[3] = new MessageFormat("              Nama : "+peg.getNama());
        MessageFormat[] footer = new MessageFormat[2];
        Date d = new Date();
        DateFormat dtform = new SimpleDateFormat("EEEE, dd MMMM yyyy HH:mm");
        footer[0] = new MessageFormat("    Dicetak pada "+dtform.format(d));
        footer[1] = new MessageFormat("    Halaman {0,number,integer}");
        job.setPrintable(new MyTablePrintable(tabelSlip, PrintMode.FIT_WIDTH, header, footer));
        if (job.printDialog())
            try {
                System.out.println("Calling PrintJob.print()");
                job.print();
                System.out.println("End PrintJob.print()");
            }
                catch (PrinterException pe) {
                    System.out.println("Error printing: " + pe);
            }
    }
    
    
    public void inisiasi(){
        delButton();
        NamaLabel.setText(peg.getNama());
        namaHai.setText(peg.getNama());
        statusLabel.setText(peg.getStatus());
        JabatanLab.setText(peg.getJabatan());
        depLab.setText(peg.getDept());
        gjPokLab.setText(formatUang(Pegawai.getGajiBersih()));
        lembur.setText(Integer.toString(peg.getLembur()));
        bonus.setText(formatUang(Pegawai.getBonus()));
        gjTotLab.setText(formatUang(peg.getGaji()));
        tc.tabelTim(tabeltim, data.getListDirektur(), data.getListManager(), 
                data.getListKaryawan(),data.getListMagang(),peg.getDept());
        loadChart();
        if(peg.getJabatan().equals("Manager")||peg.getJabatan().equals("Direktur")){
            jPanel6.setVisible(true);
        }else{
            jPanel6.setVisible(false);
        }
        tim.setText(peg.getDept());
        dep.setText(peg.getDept());
        tc.tabelSlip(tabelSlip, peg);
        OutIcon("C://Users/Dimas Adiyaksa/"
                      + "Documents/NetBeansProjects/SistemManajemenPegawai"
                      + "/src/EksternalSource/index.png");
        
    }
    
    public void loadChart(){
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        
        for(int i = 0;i<peg.getSlip().size();i++){
            dataset.setValue(peg.getSlip().get(i).getGaji(), 
                    "gaji",getBulan(ekstrakBulan(peg.getSlip().get(i).getTanggal())) );
            //System.out.println(peg.getSlip().get(i).getGaji());
            //System.out.println(getBulan(ekstrakBulan(peg.getSlip().get(i).getTanggal())));
        }
        
        JFreeChart chart = ChartFactory.createBarChart("Statistik Gaji Pegawai", "Bulan", "Gaji", dataset, PlotOrientation.VERTICAL, false, true, false); //createBarChart("Statistik Gaji Pegawai", "Gaji", "Bulan", dataset);
        CategoryPlot chrt = chart.getCategoryPlot();
        chrt.setRangeGridlinePaint(Color.BLACK);
        ChartPanel cPanel = new ChartPanel(chart);
        chartPanel1.removeAll();
        chartPanel1.add(cPanel,BorderLayout.CENTER);
        chartPanel1.validate();
    }
    
    public String getBulan(int i){
        if(i==1){
            return "Januari";
        }else if(i==2){
            return "Februari";
        }else if(i==3){
            return "Maret";
        }else if(i==4){
            return "April";
        }else if(i==5){
            return "Mei";
        }else if(i==6){
            return "Juni";
        }else if(i==7){
            return "Juli";
        }else if(i==8){
            return "Agustus";
        }else if(i==9){
            return "September";
        }else if(i==10){
            return "Oktober";
        }else if(i==11){
            return "November";
        }else if(i==12){
            return "Desember";
        }
        return null;
    }
    
    public int ekstrakBulan(String tgl){
        int bulan;
        
        bulan = Integer.parseInt(Character.toString(tgl.charAt(5))+Character.toString(tgl.charAt(6)));
        
        return bulan;
    }
    
    public int ekstrakTahun(String tgl){
        int bulan;
        
        bulan = Integer.parseInt(Character.toString(tgl.charAt(0))+Character.toString(tgl.charAt(1))+
                Character.toString(tgl.charAt(2))+Character.toString(tgl.charAt(3)));
        
        return bulan;
    }
    
    public void OutIcon(String source){
        BufferedImage img = null;
        try {
              img = ImageIO.read(new File(source));
        } catch (IOException e) {
            e.printStackTrace();
        }
        Image dimg;
        dimg = img.getScaledInstance(32, out.getHeight(),
                Image.SCALE_SMOOTH);
        ImageIcon imageIcon = new ImageIcon(dimg);
        out.setIcon(imageIcon);
    }
    
    
    public String formatUang(double uang){
        DecimalFormat kursIndonesia = (DecimalFormat) DecimalFormat.getCurrencyInstance();
        DecimalFormatSymbols formatRp = new DecimalFormatSymbols();

        formatRp.setCurrencySymbol("Rp. ");
        formatRp.setMonetaryDecimalSeparator(',');
        formatRp.setGroupingSeparator('.');
        kursIndonesia.setDecimalFormatSymbols(formatRp);
        
        return kursIndonesia.format(uang); 
    }
    
    
    private void feedUpdate(){
        new Thread(new Runnable(){
            @Override
            public void run() {
//                int i = 0;
//                int j,count = 0;
//                data.readFeed();
//                ArrayList<NewsFeed> f = data.getFeed();
//                
//                if(data.getFeed().size() == 0){
//                    feedArea.setText("Tidak ada News Feed");
//                }else{
//                    do{
//                        feedArea.setText(f.get(i%f.size()).getNews());
//                        i++;
//                        try
//                    {
//                    Thread.sleep(5000);
//                    }
//                    catch(Exception e)
//                    {
//                        System.out.println(e);
//                    }
//                    }while(true);
//                }
//                     
//                    
                } //Diisi sesuai yg mau dijalanin
            }
        ).start();
    }
     
    public void delButton(){
        if(tableJob.getSelectedRow() == -1){
            deljob.setEnabled(false);
        }else{
            deljob.setEnabled(true);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
     
  
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pegawai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Dep;
    private javax.swing.JComboBox<String> GDCBox;
    private javax.swing.JLabel GDLab;
    private javax.swing.JLabel JabatanLab;
    private javax.swing.JLabel Kontrak;
    private javax.swing.JTextField NIMPeg;
    private javax.swing.JLabel NamaLabel;
    private org.jdesktop.swingx.JXDatePicker TTL;
    private javax.swing.JTextArea address;
    private javax.swing.JLabel bonus;
    private javax.swing.JButton cetakButton;
    private javax.swing.JPanel chartPanel1;
    private org.jdesktop.swingx.JXDatePicker deadline;
    private javax.swing.JTextArea defineJob;
    private javax.swing.JButton deljob;
    private javax.swing.JLabel dep;
    private javax.swing.JLabel depLab;
    private javax.swing.JTextArea feedArea;
    private javax.swing.JLabel gjPokLab;
    private javax.swing.JLabel gjTotLab;
    private javax.swing.ButtonGroup grupCetak;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel jab;
    private javax.swing.JLabel lembur;
    private javax.swing.JLabel namaHai;
    private javax.swing.JTextField nmPeg;
    private javax.swing.JLabel out;
    private javax.swing.JComboBox<String> statusCBox1;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel statusLabel1;
    private javax.swing.JTable tabelSlip;
    private javax.swing.JTable tabeltim;
    private javax.swing.JTable tableJob;
    private javax.swing.JButton tambahPekerjaan;
    private javax.swing.JLabel tim;
    private javax.swing.JLabel timBagian;
    private javax.swing.JTextArea toPrint;
    // End of variables declaration//GEN-END:variables
}
